baseURL = "https://sangjung0.github.io/"

# 사용할 테마 이름
theme = "LoveIt"

# 웹사이트 전체 제목
title = "SangJung"

# 언어 코드 (예: "en", "ko", "jp")
languageCode = "en"
# 언어 이름 (예: "English", "한국어")
languageName = "English"
# 한국어/중국어/일본어 지원 여부. true로 하면 글자 수 기반으로 요약 생성
hasCJKLanguage = false

# SEO 스키마에만 사용되는 저작권 설명
copyright = ""

# robots.txt 파일 생성 여부 (검색 엔진 크롤러 제어)
enableRobotsTXT = true
# Git 커밋 정보를 사용해 '마지막 수정일' 등을 표시할지 여부
enableGitInfo = true
# :emoji: 와 같은 이모지 코드 사용 여부
enableEmoji = true

# 빌드 시 특정 오류들을 무시하고 계속 진행
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
ignoreErrors = []

# --- 페이지네이션(페이지 나누기) 설정 ---
[pagination]
  # /page/1 같은 별칭 URL 생성 안 함
  disableAliases = false
  # 한 페이지에 보여줄 게시물 수
  pagerSize = 10
  # 페이지 경로 (예: example.com/page/2)
  path = "page"

# --- 상단 메뉴 설정 ---
[menu]
  # [[menu.main]] 하나가 메뉴 아이템 하나에 해당
  [[menu.main]]
    weight = 1 # 메뉴 순서 (숫자가 작을수록 왼쪽)
    identifier = "posts" # 메뉴의 고유 ID
    pre = "" # 이름 앞에 붙는 아이콘 등 (HTML)
    post = "" # 이름 뒤에 붙는 아이콘 등 (HTML)
    name = "Posts" # 메뉴에 표시될 이름
    url = "/posts/" # 클릭 시 이동할 URL
    title = "" # 마우스를 올렸을 때 표시될 툴팁
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

# --- 테마의 주요 기능 설정 (params) ---
[params]
  # 사이트 기본 테마 모드 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # Git 저장소 주소 (enableGitInfo가 true일 때 사용)
  gitRepo = "sangjung0"
  # SRI(Subresource Integrity)에 사용할 해시 함수. 보안 기능
  fingerprint = ""
  # 날짜 형식
  dateFormat = "2006-01-02"
  # 소셜 미디어 공유 시 표시될 제목 (Open Graph, Twitter Cards)
  title = "SangJung's blog"
  # 소셜 미디어 공유 시 표시될 설명
  description = "This is my coding blog"
  # 소셜 미디어 공유 시 표시될 대표 이미지
  images = ["/images/profile/logo.png"]

  # --- 작성자 정보 설정 ---
  [params.author]
    name = "SangJung"
    email = "sangjung245@gmail.com"
    link = "https://github.com/sangjung0"

  # --- 헤더(상단 바) 설정 ---
  [params.header]
    desktopMode = "auto" # 데스크탑 헤더 모드 (fixed: 상단 고정)
    mobileMode = "auto" # 모바일 헤더 모드
    # 헤더 제목(로고) 설정
    [params.header.title]
      logo = "/images/profile/logo.png" # 로고 이미지 URL
      name = "SangJung's blog" # 로고 오른쪽에 표시될 이미지
      pre = "" # 이름 앞 아이콘
      post = "" # 이름 뒤 아이콘
      typeit = true # 타이핑 애니메이션 효과 사용 여부

  # --- 푸터(하단) 설정 ---
  [params.footer]
    enable = true # 푸터 활성화
    custom = "무엇을 넣을까~" # 직접 추가할 내용 (HTML)
    hugo = false # "Powered by Hugo" 문구 표시 여부
    copyright = true # 저작권 정보 표시 여부
    author = true # 작성자 정보 표시 여부
    since = 2025 # 사이트 제작 연도
    icp = "" # (중국용) ICP 정보
    license = '<a ...>CC BY-NC 4.0</a>' # 라이선스 정보

  # --- 섹션 페이지 설정 (예: /posts/ 페이지) ---
  [params.section]
    paginate = 20 # 한 페이지에 보여줄 글 개수
    dateFormat = "01-02" # 날짜 형식 (월-일)
    rss = 10 # RSS 피드에 포함할 글 개수

  # --- 리스트 페이지 설정 (예: 특정 태그나 카테고리 페이지) ---
  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  # --- 모바일 앱 아이콘 설정 (홈 화면에 추가 시) ---
  [params.app]
    title = "SangJung's blog" # 앱 아이콘 이름
    noFavicon = false # 파비콘(favicon) 링크 생략 여부
    svgFavicon = "/images/profile/favicon.svg" # SVG 파비콘
    themeColor = "#ffffff" # 안드로이드 주소창 색상
    iconColor = "#5bbad5" # 사파리 아이콘 색상
    tileColor = "#da532c" # 윈도우 타일 색상

  # --- 검색 기능 설정 ---
  [params.search]
    enable = true # 검색 기능 활성화
    type = "lunr" # 검색 엔진 종류 ["lunr", "algolia"]
    contentLength = 4000 # 검색 인덱싱할 내용의 최대 길이
    placeholder = "" # 검색창에 표시될 안내 문구
    maxResultLength = 10 # 최대 검색 결과 수
    snippetLength = 30 # 검색 결과 요약 글자 수
    highlightTag = "em" # 검색 결과 하이라이트 태그
    absoluteURL = false
    [params.search.algolia] # Algolia 검색 엔진 사용 시 설정
      index = ""
      appID = ""
      searchKey = ""

  # --- 홈페이지 설정 ---
  [params.home]
    rss = 10 # 홈페이지 RSS 피드에 포함할 글 개수
    # 홈페이지 프로필 설정
    [params.home.profile]
      enable = true # 프로필 활성화
      gravatarEmail = "" # Gravatar 이메일 (프로필 사진용)
      avatarURL = "/images/profile/logo.png" # 프로필 사진 URL
      title = "Hi" # 프로필 제목
      subtitle = "안녕하세요. 저는 프로그래밍과 AI에 관심있는 초보 프로그래머 입니다." # 프로필 부제
      typeit = true # 부제에 타이핑 애니메이션 효과 사용 여부
      social = true # 소셜 링크 표시 여부
      disclaimer = "" # 면책 조항 등 안내 문구
    # 홈페이지 게시물 목록 설정
    [params.home.posts]
      enable = true # 게시물 목록 활성화
      paginate = 6 # 한 페이지에 보여줄 글 개수
      defaultHiddenFromHomePage = false # 글의 front matter에 별도 설정이 없을 때 기본적으로 숨길지 여부

  # --- 소셜 미디어 링크 설정 ---
  [params.social]
    GitHub = "https://github.com/sangjung0"
    Linkedin = ""
    X = ""
    # ... (기타 수많은 소셜 링크)
    Email = "sangjung245@gamil.com"
    RSS = true

  # --- 개별 페이지 기본 설정 ---
  [params.page]
    hiddenFromHomePage = false # 홈페이지 목록에서 숨길지 여부
    hiddenFromSearch = false # 검색 결과에서 숨길지 여부
    twemoji = false # Twemoji (트위터 이모지) 사용 여부
    lightgallery = false # 이미지 갤러리(lightgallery.js) 사용 여부
    ruby = true # 루비 문자(윗첨자) 같은 확장 문법 사용 여부
    fraction = true # 분수 확장 문법 사용 여부
    fontawesome = true # Font Awesome 아이콘 사용 여부
    linkToMarkdown = true # 원본 마크다운 파일 링크 표시 여부
    rssFullText = false # RSS 피드에 전체 내용 포함 여부
    # 목차(Table of Contents) 설정
    [params.page.toc]
      enable = true
      keepStatic = false # 페이지 상단에 목차를 고정할지 여부
      auto = true # 사이드바의 목차가 자동으로 접힐지 여부
    # 수식(KaTeX) 설정
    [params.page.math]
      enable = true
      # copyTex = true
      # mhchem = true
      # ... (수식 관련 세부 설정)
    # 코드 블록 설정
    [params.page.code]
      copy = true # 코드 복사 버튼 표시 여부
      maxShownLines = 50 # 기본적으로 보여줄 최대 라인 수
    # 지도(Mapbox) 설정
    [params.page.mapbox]
      accessToken = "" # Mapbox API 토큰
      # ... (지도 스타일 등)
    # 소셜 공유 버튼 설정
    [params.page.share]
      enable = true
      X = true
      Facebook = true
      # ... (기타 공유 버튼 활성화 여부)
    # 댓글 기능 설정
    [params.page.comment]
      enable = false # 댓글 기능 비활성화
      [params.page.comment.disqus] # Disqus 댓글 시스템 설정
        enable = false
        shortname = ""
      [params.page.comment.giscus] # giscus 댓글 시스템 설정
        enable = false
        # ... (giscus 관련 설정)
    # 외부 라이브러리 추가 설정
    [params.page.library]
      [params.page.library.css]
        # "assets" 폴더에 있는 "custom.css"를 추가하려면 -> custom = "custom.css"
        custom = "custom.css"
      [params.page.library.js]
        # "assets" 폴더에 있는 "custom.js"를 추가하려면 -> custom = "custom.js"
    # 페이지 SEO 설정
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  # --- TypeIt 애니메이션 효과 설정 ---
  [params.typeit]
    speed = 100 # 타이핑 속도 (ms)
    cursorSpeed = 1000 # 커서 깜빡임 속도 (ms)
    cursorChar = "<" # 커서 모양
    duration = 10 # 타이핑 완료 후 커서 유지 시간 (-1: 무한)

  # --- 검색 엔진 사이트 소유 확인 설정 ---
  [params.verification]
    google = "" # 구글 Search Console 확인 코드
    bing = ""
    # ...

  # --- 사이트 전체 SEO 설정 ---
  [params.seo]
    image = "/images/profile/logo.png" # 대표 이미지
    thumbnailUrl = "/images/profile/logo.png" # 썸네일 이미지

  # --- 웹 분석 도구 설정 ---
  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "" # 구글 애널리틱스 ID
      anonymizeIP = true
      respectDoNotTrack = false

  # --- 쿠키 사용 동의 배너 설정 ---
  [params.cookieconsent]
    enable = true
    [params.cookieconsent.content]
      message = "" # 배너에 표시될 메시지
      dismiss = "" # 닫기 버튼 텍스트
      link = "" # 개인정보 정책 등 링크 텍스트

  # --- 외부 라이브러리 CDN 설정 ---
  [params.cdn]
    # jsdelivr 같은 CDN을 사용하도록 설정
    data = ""

  # --- 구형 브라우저 호환성 설정 ---
  [params.compatibility]
    polyfill = false
    objectFit = false


# --- 마크다운(Markdown) 처리 방식 설정 ---
[markup]
  # 코드 블록 문법 하이라이팅 설정
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  # Goldmark (기본 마크다운 렌더러) 설정
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true # 마크다운 안에서 HTML 태그를 직접 사용할 수 있도록 허용
  # 목차 생성 기본 설정
  [markup.tableOfContents]
    startLevel = 2 # h2 제목부터 목차에 포함
    endLevel = 6 # h6 제목까지 목차에 포함


# --- sitemap.xml 파일 설정 ---
[sitemap]
  changefreq = "weekly" # 콘텐츠 변경 빈도
  filename = "sitemap.xml"
  priority = 0.5 # 검색 엔진에 알릴 페이지 우선순위

# --- 영구 링크(URL) 구조 설정 ---
[Permalinks]
  # posts = ":year/:month/:filename" # 예: /2023/07/my-post/
  posts = ":filename" # 예: /my-post/

# --- 개인정보 보호 설정 ---
[privacy]
  [privacy.googleAnalytics]
  [privacy.twitter]
  [privacy.youtube]

# --- 출력 파일 형식 설정 (고급) ---
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# --- 페이지 종류별로 생성할 파일 형식 지정 ---
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]