name: gitblog-devcontainer
services:
    dev:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ../:/workspaces/dev
        command: ["tail", "-f", "/dev/null"]
